spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
logging:
  pattern:
    console: -%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

#spring:
#  datasource:
#    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
#  jpa:
#    show-sql: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
