spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    defer-datasource-initialization: true
logging:
  pattern:
    console: -%clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
